/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type NavSection = {
  _type: "navSection";
  hideSection?: boolean;
  hideOnDesktop?: boolean;
  heading?: string;
  links?: Array<{
    _key: string;
  } & VerticalNavLink>;
};

export type VerticalNavDivider = {
  _type: "verticalNavDivider";
  hideOnDesktop?: boolean;
  style?: string;
};

export type VerticalNavLink = {
  _type: "verticalNavLink";
  hideLink?: boolean;
  hideOnDesktop?: boolean;
  label?: string;
  linkType?: "internal" | "external";
  internalLink?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "page";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "homePage";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "termsAndConditions";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "privacyPolicy";
  };
  externalUrl?: string;
  pageSectionId?: string;
  openInNewTab?: boolean;
};

export type NavLink = {
  _type: "navLink";
  hideLink?: boolean;
  label?: string;
  linkType?: "internal" | "external";
  internalLink?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "page";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "homePage";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "termsAndConditions";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "privacyPolicy";
  };
  externalUrl?: string;
  pageSectionId?: string;
  openInNewTab?: boolean;
};

export type CtaList = Array<{
  _key: string;
} & EmbeddedCtaButton>;

export type CompanyLinksArray = {
  _type: "companyLinksArray";
  socialLinksArray?: Array<{
    url?: string;
    detectedPlatform?: string;
    platform?: "genericLink";
    customTitle?: string;
    hideFromFooter?: boolean;
    _type: "socialLinkItem";
    _key: string;
  }>;
};

export type ContactForm = {
  _type: "contactForm";
  placeholder?: string;
};

export type ItemList = {
  _type: "itemList";
  alignment?: "inherit" | "left" | "center" | "right";
  items?: Array<{
    text?: string;
    icon?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    _type: "listItem";
    _key: string;
  }>;
};

export type CheckList = {
  _type: "checkList";
  items?: Array<{
    text?: string;
    _type: "checkListItem";
    _key: string;
  }>;
};

export type BlockListWithStats = {
  _type: "blockListWithStats";
  items?: Array<{
    leftContent?: string;
    rightContent?: string;
    _type: "blockListItem";
    _key: string;
  }>;
};

export type IconList = {
  _type: "iconList";
  layout?: "horizontal" | "vertical";
  items?: Array<{
    iconType?: "library" | "custom";
    icon?: string;
    customImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    description?: string;
    _type: "iconListItem";
    _key: string;
  }>;
};

export type CompanyLinksBlock = {
  _type: "companyLinksBlock";
  blockAdded?: string;
};

export type HomeHeroCtaButton = {
  _type: "homeHeroCtaButton";
  text?: string;
  linkType?: "internal" | "external";
  internalLink?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "page";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "homePage";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "termsAndConditions";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "privacyPolicy";
  };
  externalUrl?: string;
  pageSectionId?: string;
  openInNewTab?: boolean;
};

export type EmbeddedCtaButton = {
  _type: "embeddedCtaButton";
  text?: string;
  variant?: "filled" | "outline-light" | "outline-dark" | "text-link";
  linkType?: "internal" | "external";
  internalLink?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "page";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "homePage";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "termsAndConditions";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "privacyPolicy";
  };
  externalUrl?: string;
  pageSectionId?: string;
  openInNewTab?: boolean;
};

export type CtaCalloutLink = {
  _type: "ctaCalloutLink";
  heading?: string;
  text?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  linkType?: "internal" | "external";
  internalLink?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "page";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "homePage";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "termsAndConditions";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "privacyPolicy";
  };
  externalUrl?: string;
  pageSectionId?: string;
  openInNewTab?: boolean;
};

export type CtaButton = {
  _type: "ctaButton";
  text?: string;
  variant?: "filled" | "outline-light" | "outline-dark" | "text-link";
  alignment?: "inherit" | "left" | "center" | "right";
  linkType?: "internal" | "external";
  internalLink?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "page";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "homePage";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "termsAndConditions";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "privacyPolicy";
  };
  externalUrl?: string;
  pageSectionId?: string;
  openInNewTab?: boolean;
};

export type TwoColumnLayout = {
  _type: "twoColumnLayout";
  verticallyCenter?: boolean;
  leftColumn?: Array<{
    _key: string;
  } & RichText | {
    _key: string;
  } & Statement | {
    _key: string;
  } & Quote | {
    _key: string;
  } & Divider | {
    _key: string;
  } & ImageBlock | {
    _key: string;
  } & ImageGallery | {
    _key: string;
  } & YouTubeVideo | {
    _key: string;
  } & CtaButton | {
    _key: string;
  } & CtaCalloutLink | {
    _key: string;
  } & IconList | {
    _key: string;
  } & BlockListWithStats | {
    _key: string;
  } & CheckList | {
    _key: string;
  } & ItemList | {
    _key: string;
  } & ContactForm | {
    _key: string;
  } & CompanyLinksBlock | {
    _key: string;
  } & Card>;
  rightColumn?: Array<{
    _key: string;
  } & RichText | {
    _key: string;
  } & Statement | {
    _key: string;
  } & Quote | {
    _key: string;
  } & Divider | {
    _key: string;
  } & ImageBlock | {
    _key: string;
  } & ImageGallery | {
    _key: string;
  } & YouTubeVideo | {
    _key: string;
  } & CtaButton | {
    _key: string;
  } & CtaCalloutLink | {
    _key: string;
  } & IconList | {
    _key: string;
  } & BlockListWithStats | {
    _key: string;
  } & CheckList | {
    _key: string;
  } & ItemList | {
    _key: string;
  } & ContactForm | {
    _key: string;
  } & CompanyLinksBlock | {
    _key: string;
  } & Card>;
};

export type Statement = {
  _type: "statement";
  text?: string;
};

export type Quote = {
  _type: "quote";
  text?: string;
  attribution?: string;
  textAlign?: "inherit" | "left" | "center" | "right";
};

export type YouTubeVideo = {
  _type: "youTubeVideo";
  url?: string;
};

export type ImageGallery = {
  _type: "imageGallery";
  columns?: "2" | "3" | "4";
  showCaptionsBelowImages?: boolean;
  images?: Array<{
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    caption?: string;
    _key: string;
  }>;
};

export type ImageBlock = {
  _type: "imageBlock";
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  size?: "full" | "small";
  caption?: string;
};

export type GridLayout = {
  _type: "gridLayout";
  columns?: "2" | "3" | "4";
  content?: Array<{
    _key: string;
  } & RichText | {
    _key: string;
  } & Statement | {
    _key: string;
  } & Quote | {
    _key: string;
  } & Divider | {
    _key: string;
  } & ImageBlock | {
    _key: string;
  } & ImageGallery | {
    _key: string;
  } & YouTubeVideo | {
    _key: string;
  } & CtaButton | {
    _key: string;
  } & CtaCalloutLink | {
    _key: string;
  } & IconList | {
    _key: string;
  } & BlockListWithStats | {
    _key: string;
  } & CheckList | {
    _key: string;
  } & ItemList | {
    _key: string;
  } & ContactForm | {
    _key: string;
  } & CompanyLinksBlock | {
    _key: string;
  } & Card>;
};

export type Card = {
  _type: "card";
  visualStyle?: "light" | "dark";
  title?: string;
  subtitle?: string;
  imageType?: "none" | "banner" | "icon";
  iconNoImageLayoutStyle?: "stacked" | "row";
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  content?: Array<{
    _key: string;
  } & RichText | {
    _key: string;
  } & Statement | {
    _key: string;
  } & Quote | {
    _key: string;
  } & Divider | {
    _key: string;
  } & ImageBlock | {
    _key: string;
  } & ImageGallery | {
    _key: string;
  } & YouTubeVideo | {
    _key: string;
  } & CtaButton | {
    _key: string;
  } & CtaCalloutLink | {
    _key: string;
  } & IconList | {
    _key: string;
  } & BlockListWithStats | {
    _key: string;
  } & CheckList | {
    _key: string;
  } & ItemList | {
    _key: string;
  } & ContactForm | {
    _key: string;
  } & CompanyLinksBlock>;
};

export type RichText = {
  _type: "richText";
  isCallout?: boolean;
  textAlign?: "inherit" | "left" | "center" | "right";
  content?: BlockContent;
};

export type Divider = {
  _type: "divider";
  style?: string;
};

export type ContentWrapper = {
  _type: "contentWrapper";
  backgroundStyle?: "" | "smokey-1" | "smokey-2" | "smokey-3" | "smokey-4" | "smokey-5" | "smokey-6" | "smokey-7" | "smokey-8";
  useCompactGap?: boolean;
  content?: Array<{
    _key: string;
  } & RichText | {
    _key: string;
  } & Statement | {
    _key: string;
  } & Quote | {
    _key: string;
  } & Divider | {
    _key: string;
  } & ImageBlock | {
    _key: string;
  } & ImageGallery | {
    _key: string;
  } & YouTubeVideo | {
    _key: string;
  } & CtaButton | {
    _key: string;
  } & CtaCalloutLink | {
    _key: string;
  } & IconList | {
    _key: string;
  } & BlockListWithStats | {
    _key: string;
  } & CheckList | {
    _key: string;
  } & ItemList | {
    _key: string;
  } & ContactForm | {
    _key: string;
  } & CompanyLinksBlock | {
    _key: string;
  } & TwoColumnLayout | {
    _key: string;
  } & GridLayout | {
    _key: string;
  } & Card>;
};

export type SubSubSection = {
  _type: "subSubSection";
  hideSection?: boolean;
  title?: string;
  anchorId?: string;
  content?: Array<{
    _key: string;
  } & RichText | {
    _key: string;
  } & Statement | {
    _key: string;
  } & Quote | {
    _key: string;
  } & Divider | {
    _key: string;
  } & ImageBlock | {
    _key: string;
  } & ImageGallery | {
    _key: string;
  } & YouTubeVideo | {
    _key: string;
  } & CtaButton | {
    _key: string;
  } & CtaCalloutLink | {
    _key: string;
  } & IconList | {
    _key: string;
  } & BlockListWithStats | {
    _key: string;
  } & CheckList | {
    _key: string;
  } & ItemList | {
    _key: string;
  } & ContactForm | {
    _key: string;
  } & CompanyLinksBlock | {
    _key: string;
  } & TwoColumnLayout | {
    _key: string;
  } & GridLayout | {
    _key: string;
  } & Card>;
};

export type SubSection = {
  _type: "subSection";
  hideSection?: boolean;
  title?: string;
  anchorId?: string;
  content?: Array<{
    _key: string;
  } & SubSubSection | {
    _key: string;
  } & RichText | {
    _key: string;
  } & Statement | {
    _key: string;
  } & Quote | {
    _key: string;
  } & Divider | {
    _key: string;
  } & ImageBlock | {
    _key: string;
  } & ImageGallery | {
    _key: string;
  } & YouTubeVideo | {
    _key: string;
  } & CtaButton | {
    _key: string;
  } & CtaCalloutLink | {
    _key: string;
  } & IconList | {
    _key: string;
  } & BlockListWithStats | {
    _key: string;
  } & CheckList | {
    _key: string;
  } & ItemList | {
    _key: string;
  } & ContactForm | {
    _key: string;
  } & CompanyLinksBlock | {
    _key: string;
  } & TwoColumnLayout | {
    _key: string;
  } & GridLayout | {
    _key: string;
  } & Card>;
};

export type PageSection = {
  _type: "pageSection";
  hideSection?: boolean;
  title?: string;
  anchorId?: string;
  subtitle?: string;
  topText?: string;
  useCompactGap?: boolean;
  backgroundStyle?: "" | "smokey-1" | "smokey-2" | "smokey-3" | "smokey-4" | "smokey-5" | "smokey-6" | "smokey-7" | "smokey-8";
  content?: Array<{
    _key: string;
  } & SubSection | {
    _key: string;
  } & RichText | {
    _key: string;
  } & Statement | {
    _key: string;
  } & Quote | {
    _key: string;
  } & Divider | {
    _key: string;
  } & ImageBlock | {
    _key: string;
  } & ImageGallery | {
    _key: string;
  } & YouTubeVideo | {
    _key: string;
  } & CtaButton | {
    _key: string;
  } & CtaCalloutLink | {
    _key: string;
  } & IconList | {
    _key: string;
  } & BlockListWithStats | {
    _key: string;
  } & CheckList | {
    _key: string;
  } & ItemList | {
    _key: string;
  } & ContactForm | {
    _key: string;
  } & CompanyLinksBlock | {
    _key: string;
  } & TwoColumnLayout | {
    _key: string;
  } & GridLayout | {
    _key: string;
  } & Card>;
};

export type PageBuilder = Array<{
  _key: string;
} & PageSection | {
  _key: string;
} & ContentWrapper>;

export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  footerMessages?: Array<{
    title?: string;
    message?: string;
    _key: string;
  }>;
  quickLinks?: Array<{
    label?: string;
    linkType?: "internal" | "external";
    internalLink?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "page";
    } | {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "homePage";
    } | {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "termsAndConditions";
    } | {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "privacyPolicy";
    };
    externalUrl?: string;
    pageSectionId?: string;
    openInNewTab?: boolean;
    _key: string;
  }>;
  copyrightText?: string;
};

export type Header = {
  _id: string;
  _type: "header";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  horizontalNav?: Array<{
    _key: string;
  } & NavLink>;
  horizontalNavCtas?: CtaList;
  showVerticalNavOnDesktop?: boolean;
  verticalNav?: Array<{
    _key: string;
  } & NavSection>;
  verticalNavCtas?: CtaList;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "body-3xl" | "body-2xl" | "body-xl" | "body-lg" | "body-sm" | "body-xs" | "standout";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  } | {
    _key: string;
  } & Color>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type PrivacyPolicy = {
  _id: string;
  _type: "privacyPolicy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hide?: boolean;
  title?: string;
  topText?: string;
  content?: Array<{
    _key: string;
  } & PageSection | {
    _key: string;
  } & RichText | {
    _key: string;
  } & Statement | {
    _key: string;
  } & Quote | {
    _key: string;
  } & Divider | {
    _key: string;
  } & ImageBlock | {
    _key: string;
  } & ImageGallery | {
    _key: string;
  } & YouTubeVideo | {
    _key: string;
  } & CtaButton | {
    _key: string;
  } & CtaCalloutLink | {
    _key: string;
  } & IconList | {
    _key: string;
  } & BlockListWithStats | {
    _key: string;
  } & CheckList | {
    _key: string;
  } & ItemList | {
    _key: string;
  } & ContactForm | {
    _key: string;
  } & CompanyLinksBlock | {
    _key: string;
  } & TwoColumnLayout | {
    _key: string;
  } & GridLayout | {
    _key: string;
  } & Card>;
};

export type TermsAndConditions = {
  _id: string;
  _type: "termsAndConditions";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hide?: boolean;
  title?: string;
  topText?: string;
  content?: Array<{
    _key: string;
  } & PageSection | {
    _key: string;
  } & RichText | {
    _key: string;
  } & Statement | {
    _key: string;
  } & Quote | {
    _key: string;
  } & Divider | {
    _key: string;
  } & ImageBlock | {
    _key: string;
  } & ImageGallery | {
    _key: string;
  } & YouTubeVideo | {
    _key: string;
  } & CtaButton | {
    _key: string;
  } & CtaCalloutLink | {
    _key: string;
  } & IconList | {
    _key: string;
  } & BlockListWithStats | {
    _key: string;
  } & CheckList | {
    _key: string;
  } & ItemList | {
    _key: string;
  } & ContactForm | {
    _key: string;
  } & CompanyLinksBlock | {
    _key: string;
  } & TwoColumnLayout | {
    _key: string;
  } & GridLayout | {
    _key: string;
  } & Card>;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  subtitle?: string;
  content?: Array<{
    _key: string;
  } & PageSection | {
    _key: string;
  } & RichText | {
    _key: string;
  } & Statement | {
    _key: string;
  } & Quote | {
    _key: string;
  } & Divider | {
    _key: string;
  } & ImageBlock | {
    _key: string;
  } & ImageGallery | {
    _key: string;
  } & YouTubeVideo | {
    _key: string;
  } & CtaButton | {
    _key: string;
  } & CtaCalloutLink | {
    _key: string;
  } & IconList | {
    _key: string;
  } & BlockListWithStats | {
    _key: string;
  } & CheckList | {
    _key: string;
  } & ItemList | {
    _key: string;
  } & ContactForm | {
    _key: string;
  } & CompanyLinksBlock | {
    _key: string;
  } & TwoColumnLayout | {
    _key: string;
  } & GridLayout | {
    _key: string;
  } & Card>;
  hasClosingCard?: boolean;
  closingCard?: Card;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroStyle?: "default" | "background-images" | "video";
  heroImages?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  heroVideo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  };
  heroImageTransitionDuration?: number;
  heroTextColor?: "black" | "white";
  heroDefaultContentPosition?: "center-left" | "center-right";
  heroContentPosition?: "top-left" | "top-center" | "top-right" | "center-left" | "center-center" | "center-right" | "bottom-left" | "bottom-center" | "bottom-right";
  h1Title?: string;
  heroTitle?: BlockContent;
  heroCallToActionList?: CtaList;
  hideScrollIndicator?: boolean;
  content?: PageBuilder;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type ContactFormSettings = {
  _id: string;
  _type: "contactFormSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  subtitle?: string;
  messagePlaceholder?: string;
  successHeading?: string;
  successMessage?: string;
  emailGreeting?: string;
  emailIntroMessage?: string;
  emailOutroMessage?: string;
};

export type CompanyLinks = {
  _id: string;
  _type: "companyLinks";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  companyLinks?: CompanyLinksArray;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteTitle?: string;
  siteTagline?: string;
  siteDescription?: string;
  seoKeywords?: string;
  defaultOgImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Color = {
  _type: "color";
  hex?: string;
  alpha?: number;
  hsl?: HslaColor;
  hsv?: HsvaColor;
  rgb?: RgbaColor;
};

export type RgbaColor = {
  _type: "rgbaColor";
  r?: number;
  g?: number;
  b?: number;
  a?: number;
};

export type HsvaColor = {
  _type: "hsvaColor";
  h?: number;
  s?: number;
  v?: number;
  a?: number;
};

export type HslaColor = {
  _type: "hslaColor";
  h?: number;
  s?: number;
  l?: number;
  a?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = NavSection | VerticalNavDivider | VerticalNavLink | NavLink | CtaList | CompanyLinksArray | ContactForm | ItemList | CheckList | BlockListWithStats | IconList | CompanyLinksBlock | HomeHeroCtaButton | EmbeddedCtaButton | CtaCalloutLink | CtaButton | TwoColumnLayout | Statement | Quote | YouTubeVideo | ImageGallery | ImageBlock | GridLayout | Card | RichText | Divider | ContentWrapper | SubSubSection | SubSection | PageSection | PageBuilder | Footer | Header | BlockContent | PrivacyPolicy | TermsAndConditions | Page | Slug | HomePage | SanityImageCrop | SanityImageHotspot | ContactFormSettings | CompanyLinks | SiteSettings | Color | RgbaColor | HsvaColor | HslaColor | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
